=== MatthewMawhinney/xml-support-system/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="email" type="email"/>
              <xs:element name="dateJoined" type="xs:date"/>
              <xs:element name="username" type="xs:string"/>
              <xs:element name="password" type="xs:string"/>
              <xs:element name="location">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="country" type="xs:string"/>
                    <xs:element name="timezone" type="timezone"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="role" type="role" use="required"/>
            <xs:attribute name="id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="role">
    <xs:restriction base="xs:string">
      <xs:enumeration value="client"/>
      <xs:enumeration value="support"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="email">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-z0-9]{2,20}@[a-zA-z0-9]{2,20}.[a-zA-z]{2,20}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="open"/>
      <xs:enumeration value="resolved"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="timezone">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-z0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MatthewMawhinney/xml-support-system/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
  <user role="client" id="34782">
    <name>
      <first>Matt</first>
      <last>Mawhinney</last>
    </name>
    <email>mattmawhinney@live.com</email>
    <dateJoined>2018-02-01</dateJoined>
    <username>MattMawhinney</username>
    <password>mattspassword1</password>
    <location>
      <country>Canada</country>
      <timezone>EST</timezone>
    </location>
  </user>
  <user role="client" id="69045">
    <name>
      <first>Bernie</first>
      <last>Monette</last>
    </name>
    <email>berniemonette@humbermail.ca</email>
    <dateJoined>2018-02-03</dateJoined>
    <username>BernieM</username>
    <password>webdev2</password>
    <location>
      <country>Canada</country>
      <timezone>EST</timezone>
    </location>
  </user>
  <user role="client" id="25739">
    <name>
      <first>John</first>
      <last>Douglas</last>
    </name>
    <email>johnnyd@gmail.com</email>
    <dateJoined>2018-01-28</dateJoined>
    <username>JohnD45</username>
    <password>Sportsfan3</password>
    <location>
      <country>Canada</country>
      <timezone>MTN</timezone>
    </location>
  </user>
  <user role="support" id="00007">
    <name>
      <first>Joanna</first>
      <last>Kommala</last>
    </name>
    <email>joannak@humbermail.ca</email>
    <dateJoined>2018-01-12</dateJoined>
    <username>HumberJoanna</username>
    <password>humber123</password>
    <location>
      <country>Canada</country>
      <timezone>EST</timezone>
    </location>
  </user>
</users>
